apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\tzahi\Documents\YoutubeDL-Material\kompose.exe --file .\docker-compose.yml
      convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ytdl-material
  name: ytdl-material
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ytdl-material
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\tzahi\Documents\YoutubeDL-Material\kompose.exe --file
          .\docker-compose.yml convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: ytdl-material
    spec:
      containers:
      - env:
        - name: ALLOW_CONFIG_MUTATIONS
          value: "true"
        image: tzahi12345/youtubedl-material:latest
        imagePullPolicy: ""
        name: ytdl-material
        ports:
        - containerPort: 17442
          name: http
        resources: {}
        volumeMounts:
        - mountPath: /app/appdata
          name: ytdl-material-claim-appdata
        - mountPath: /app/audio
          name: ytdl-material-claim-audio
        - mountPath: /app/video
          name: ytdl-material-claim-video
        - mountPath: /app/subscriptions
          name: ytdl-material-claim-subscriptions
        - mountPath: /app/users
          name: ytdl-material-claim-users
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: ytdl-material-claim-appdata
        persistentVolumeClaim:
          claimName: ytdl-material-claim-appdata
      - name: ytdl-material-claim-audio
        persistentVolumeClaim:
          claimName: ytdl-material-claim-audio
      - name: ytdl-material-claim-video
        persistentVolumeClaim:
          claimName: ytdl-material-claim-video
      - name: ytdl-material-claim-subscriptions
        persistentVolumeClaim:
          claimName: ytdl-material-claim-subscriptions
      - name: ytdl-material-claim-users
        persistentVolumeClaim:
          claimName: ytdl-material-claim-users
status: {}
