apiVersion: v1
entries:
  youtubedl-material:
  - apiVersion: v1
    created: "2020-12-31T05:32:00.6730825-05:00"
    description: A generated Helm Chart for youtubedl-material from Skippbox Kompose
    digest: b53abe88813192efa68dde62dbe3271f60972233b0f605987200b24d050219f2
    keywords:
    - youtubedl-material
    name: youtubedl-material
    urls:
    - youtubedl-material-0.0.1.tgz
    version: 0.0.1
generated: "2020-12-31T05:32:00.667049-05:00"
