apiVersion: v1
entries:
  youtubedl-material:
  - apiVersion: v1
    created: "2020-12-31T16:28:52.6357354-05:00"
    description: A Material Design frontend for youtube-dl
    digest: 79101bce7cbea7b1d19ea12c9826a82b0d64208826ed51929e46dbcb005766ce
    home: https://github.com/Tzahi12345/YoutubeDL-Material/
    icon: https://i.imgur.com/IKOlr0N.png
    keywords:
    - youtubedl-material
    - youtube-dl
    maintainers:
    - email: IsaacMGrynsztein@gmail.com
      name: tzahi12345
    name: youtubedl-material
    sources:
    - https://github.com/Tzahi12345/YoutubeDL-Material/
    urls:
    - youtubedl-material-0.0.1.tgz
    version: 0.0.1
generated: "2020-12-31T16:28:52.6337326-05:00"
