apiVersion: v1
entries:
  youtubedl-material:
  - apiVersion: v1
    created: "2020-12-31T01:55:22.0787497-05:00"
    description: A generated Helm Chart for youtubedl-material from Skippbox Kompose
    digest: ad0b0b00c4d96a79aba56c3a5c24c1bb659561becc99206175de9c73b8e0cde5
    keywords:
    - youtubedl-material
    name: youtubedl-material
    urls:
    - youtubedl-material-0.0.1.tgz
    version: 0.0.1
generated: "2020-12-31T01:55:22.0777453-05:00"
