apiVersion: v1
entries:
  youtubedl-material:
  - apiVersion: v1
    created: "2020-12-31T16:38:39.1740917-05:00"
    description: A Material Design frontend for youtube-dl
    digest: 2236ee23d0ef2274299fe980d01d31c8e85e0e58497f6c873cb1baca98fe4db7
    home: https://github.com/Tzahi12345/YoutubeDL-Material/
    icon: https://i.imgur.com/IKOlr0N.png
    keywords:
    - youtubedl-material
    - youtube-dl
    maintainers:
    - email: IsaacMGrynsztein@gmail.com
      name: tzahi12345
    name: youtubedl-material
    sources:
    - https://github.com/Tzahi12345/YoutubeDL-Material/
    urls:
    - youtubedl-material-0.0.1.tgz
    version: 0.0.1
generated: "2020-12-31T16:38:39.1721251-05:00"
