apiVersion: v1
entries:
  youtubedl-material:
  - apiVersion: v1
    created: "2020-12-30T19:29:17.1665063-05:00"
    description: A generated Helm Chart for youtubedl-material from Skippbox Kompose
    digest: b02eeb73e6a88df0a650f8d18b76acff2ef972cbaa6800ab89c428b008eebdce
    keywords:
    - youtubedl-material
    name: youtubedl-material
    urls:
    - youtubedl-material-0.0.1.tgz
    version: 0.0.1
generated: "2020-12-30T19:29:17.1654734-05:00"
