apiVersion: v1
entries:
  youtubedl-material:
  - apiVersion: v1
    created: "2020-12-31T16:50:44.321063-05:00"
    description: A Material Design frontend for youtube-dl
    digest: 2bda936589330e7f13c88cbaf29a397766abdf2994a3b5f4fed24602ea606e15
    home: https://github.com/Tzahi12345/YoutubeDL-Material/
    icon: https://i.imgur.com/IKOlr0N.png
    keywords:
    - youtubedl-material
    - youtube-dl
    maintainers:
    - email: IsaacMGrynsztein@gmail.com
      name: tzahi12345
    name: youtubedl-material
    sources:
    - https://github.com/Tzahi12345/YoutubeDL-Material/
    urls:
    - youtubedl-material-0.0.1.tgz
    version: 0.0.1
generated: "2020-12-31T16:50:44.321063-05:00"
