apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\tzahi\Documents\YoutubeDL-Material\kompose.exe --file .\docker-compose.yml
      convert --volumes hostPath -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ytdl-material
  name: ytdl-material
spec:
  ports:
  - name: "8998"
    port: 8998
    targetPort: 17442
  selector:
    io.kompose.service: ytdl-material
status:
  loadBalancer: {}
